// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../en-pages.js")

type Info = GetInfo<{
  file: "routes/en-pages.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-services";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-contact";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-faq";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-blog-index";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-articles";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-why-worbimed";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-hair-transplant";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-cost";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-reviews";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-before-after";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-timeline";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-10y";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-safe";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-bw";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-birmingham";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-ht-istanbul";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-afro";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-unshaven";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-forehead";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-why-turkey";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-fue";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-dhi";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-beard";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-eyebrow";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-women";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-privacy";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "en-eminem";
  module: typeof import("../en-pages.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "routes/en-pages";
  module: typeof import("../en-pages.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // ServerHydrateFallback
  export type ServerHydrateFallbackProps = Annotations["ServerHydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ServerComponent
  export type ServerComponentProps = Annotations["ServerComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];

  // ServerErrorBoundary
  export type ServerErrorBoundaryProps = Annotations["ServerErrorBoundaryProps"];
}