// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog/:category": {
    params: {
      "category": string;
    };
  };
  "/fr/*": {
    params: {
      "*": string;
    };
  };
  "/ru/*": {
    params: {
      "*": string;
    };
  };
  "/it/*": {
    params: {
      "*": string;
    };
  };
  "/tr/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog/:category" | "/fr/*" | "/ru/*" | "/it/*" | "/tr/*" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/blog-category.tsx": {
    id: "routes/blog-category";
    page: "/blog/:category";
  };
  "routes/lang-pages.tsx": {
    id: "routes/fr-pages";
    page: "/fr/*";
  } | {
    id: "routes/ru-pages";
    page: "/ru/*";
  } | {
    id: "routes/it-pages";
    page: "/it/*";
  } | {
    id: "routes/tr-pages";
    page: "/tr/*";
  };
  "routes/en-pages.tsx": {
    id: "routes/en-pages";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/blog-category": typeof import("./app/routes/blog-category.tsx");
  "routes/fr-pages": typeof import("./app/routes/lang-pages.tsx");
  "routes/ru-pages": typeof import("./app/routes/lang-pages.tsx");
  "routes/it-pages": typeof import("./app/routes/lang-pages.tsx");
  "routes/tr-pages": typeof import("./app/routes/lang-pages.tsx");
  "routes/en-pages": typeof import("./app/routes/en-pages.tsx");
};